version: '3.8'

services:
  # 1. Zookeeper 서비스 (Kafka가 의존)
  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.3
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  # 2. Kafka 서비스
  kafka:
    image: confluentinc/cp-kafka:7.5.3
    container_name: kafka
    ports:
      # WSL 및 Windows의 Spring Boot 앱에서 접속하기 위한 포트
      - "9092:9092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      # 중요: 외부(localhost)에서 접속할 주소를 알려주는 설정
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT

  # 3. MySQL 서비스 (쓰기 DB)
  mysql:
    image: mysql:8.0
    container_name: mysql_db
    ports:
      - "3306:3306"
    environment:
      # command-service의 application.yml에 설정한 값과 동일하게 맞추세요.
      MYSQL_ROOT_PASSWORD: pass1234
      MYSQL_DATABASE: todo_write_db
    volumes:
      - mysql-data:/var/lib/mysql

  # 4. MongoDB 서비스 (읽기 DB)
  mongo:
    image: mongo:latest
    container_name: mongo_db
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

# 데이터 유지를 위한 볼륨 설정
volumes:
  mysql-data:
  mongo-data: