apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

namespace: prod

patches:
- path: patch-command-replicas.yaml
- path: patch-query-replicas.yaml
- path: patch-frontend-replicas.yaml
- path: patch-frontend-nodeport.yaml # <-- 운영환경에서는 노트포트 30080으로 지정
