apiVersion: apps/v1
kind: Deployment
metadata:
  name: command-service-deployment
spec:
  replicas: 2
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: query-service-deployment
spec:
  replicas: 2
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
spec:
  replicas: 2
