apiVersion: v1
kind: ConfigMap
metadata:
  name: app-configmap
data:
  MYSQL_HOST: "mysql-service"
  MYSQL_PORT: "3306"
  
  MONGO_HOST: "mongo-service"
  MONGO_PORT: "27017"
  
  KAFKA_BOOTSTRAP_SERVERS: "kafka-service:9092"
