apiVersion: apps/v1
kind: Deployment
metadata:
  name: command-service-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: command-service
  template:
    metadata:
      labels:
        app: command-service
    spec:
      initContainers:
      - name: wait-for-mysql
        image: busybox:1.36
        # ✅ 환경 변수를 사용하여 대기
        command: ["sh", "-c", "until nc -z -w 2 $MYSQL_HOST $MYSQL_PORT; do echo waiting for mysql; sleep 2; done;"]
        env:
        - name: MYSQL_HOST
          valueFrom:
            configMapKeyRef:
              name: app-configmap
              key: MYSQL_HOST
        - name: MYSQL_PORT
          valueFrom:
            configMapKeyRef:
              name: app-configmap
              key: MYSQL_PORT
      - name: wait-for-kafka
        image: busybox:1.36
        command: ["sh", "-c", "until nc -z -w 2 kafka-service 9092; do echo waiting for kafka; sleep 2; done;"]

      containers:
      - name: command-service
        image: kyla333/command-service:latest
        ports:
        - containerPort: 8080
        readinessProbe:
          httpGet:
            path: /actuator/health/readiness
            port: 8080
          # 애플리케이션이 트래픽을 받을 준비가 될 때까지 충분히 기다립니다.
          initialDelaySeconds: 60
          periodSeconds: 10
          failureThreshold: 3
        livenessProbe:
          httpGet:
            path: /actuator/health/liveness
            port: 8080
          # 애플리케이션이 완전히 구동될 때까지 더 넉넉하게 기다립니다.
          initialDelaySeconds: 90
          periodSeconds: 10
          failureThreshold: 3
        envFrom:
        - configMapRef:
            name: app-configmap
        env:
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: password

