controller:
  serviceType: NodePort
  servicePort: 8080
  nodePort: 32000

  installPlugins:
    - kubernetes:latest
    - workflow-aggregator:latest
    - git:latest
    - configuration-as-code:latest

  resources:
    requests:
      cpu: "50m"
      memory: "256Mi"
    limits:
      cpu: "2000m"
      memory: "4Gi"

  containerEnv:
    - name: JENKINS_UC
      value: https://updates.jenkins.io/update-center.json
    - name: JENKINS_UC_EXPERIMENTAL
      value: https://updates.jenkins.io/experimental/update-center.json
    - name: JENKINS_INCREMENTALS_REPO_MIRROR
      value: https://repo.jenkins-ci.org/incrementals

agent:
  enabled: false

persistence:
  enabled: true
  storageClass: "nfs-storage"
  size: "8Gi"
  accessMode: ReadWriteOnce
