server:
  port: 8081

spring:
  application:
    name: query-service

  data:
    mongodb:
      uri: mongodb://${MONGO_HOST}:${MONGO_PORT}/todo_read_db

  # Kafka 접속 정보: 반드시 localhost를 사용해야 합니다.
  kafka:
    consumer:
      bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}
      group-id: todo-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "com.hyundai.todo.dto"
