apiVersion: apps/v1
kind: Deployment
metadata:
  name: query-service-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: query-service
  template:
    metadata:
      labels:
        app: query-service
    spec:
      initContainers:
      - name: wait-for-mongo
        image: busybox:1.36
        # ✅ 환경 변수를 사용하여 대기
        command: ["sh", "-c", "until nc -z -w 2 $MONGO_HOST $MONGO_PORT; do echo waiting for mongo; sleep 2; done;"]
        env:
        - name: MONGO_HOST
          valueFrom:
            configMapKeyRef:
              name: app-configmap
              key: MONGO_HOST
        - name: MONGO_PORT
          valueFrom:
            configMapKeyRef:
              name: app-configmap
              key: MONGO_PORT
      - name: wait-for-kafka
        image: busybox:1.36
        command: ["sh", "-c", "until nc -z -w 2 kafka-service 9092; do echo waiting for kafka; sleep 2; done;"]

      containers:
      - name: query-service
        image: kyla333/query-service:latest
        ports:
        - containerPort: 8081
        envFrom:
        - configMapRef:
            name: app-configmap

