apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

namespace: dev

images:
- name: kyla333/command-service
  newTag: latest
- name: kyla333/query-service
  newTag: latest
- name: kyla333/todo-frontend
  newTag: latest

# ✅ 분리된 3개의 패치 파일을 모두 지정합니다.
patches:
- path: patch-command-replicas.yaml
- path: patch-query-replicas.yaml
- path: patch-frontend-replicas.yaml

# NFS Provisioner ClusterRoleBinding 네임스페이스 자동 치환
replacements:
  - source:
      kind: ServiceAccount
      name: nfs-client-provisioner
      fieldPath: metadata.namespace
    targets:
      - select:
          kind: ClusterRoleBinding
          name: run-nfs-client-provisioner
        fieldPaths:
          - subjects.[name=nfs-client-provisioner].namespace

